### ISSUE TITLE
Crash on Training Attempt

### ISSUE THREAD

**Issue by ndumais** [mDuval1/bumble-bot#2]
Alright, so after playing around with the code a bit more, I managed to fix most of the issues but I get the following error when I try to train the model. Keep in mind I stopped (pressing CTRL+C) after 4 profiles this time since I ran out of swipes testing things out:
 
>  C:\Users\Public\Public Apps\bumble-bot-main>main.py --mode TRAIN
> 2022-10-18 16:53:03.951579: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
> 2022-10-18 16:53:03.951665: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> 2022-10-18 16:53:05.858186: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
> 2022-10-18 16:53:05.858270: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
> 2022-10-18 16:53:05.860825: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-QT5RMCM
> 2022-10-18 16:53:05.860918: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-QT5RMCM
> 2022-10-18 16:53:05.861368: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
> 2022-10-18 16:53:07.156090: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:776] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Found an unshardable source dataset: name: "TensorSliceDataset/_2"
> op: "TensorSliceDataset"
> input: "Placeholder/_0"
> input: "Placeholder/_1"
> attr {
>   key: "Toutput_types"
>   value {
>     list {
>       type: DT_STRING
>       type: DT_INT32
>     }
>   }
> }
> attr {
>   key: "_cardinality"
>   value {
>     i: 1
>   }
> }
> attr {
>   key: "is_files"
>   value {
>     b: false
>   }
> }
> attr {
>   key: "metadata"
>   value {
>     s: "\n\024TensorSliceDataset:0"
>   }
> }
> attr {
>   key: "output_shapes"
>   value {
>     list {
>       shape {
>       }
>       shape {
>       }
>     }
>   }
> }
> experimental_type {
>   type_id: TFT_PRODUCT
>   args {
>     type_id: TFT_DATASET
>     args {
>       type_id: TFT_PRODUCT
>       args {
>         type_id: TFT_TENSOR
>         args {
>           type_id: TFT_STRING
>         }
>       }
>       args {
>         type_id: TFT_TENSOR
>         args {
>           type_id: TFT_INT32
>         }
>       }
>     }
>   }
>   args {
>     type_id: TFT_DATASET
>     args {
>       type_id: TFT_PRODUCT
>       args {
>         type_id: TFT_TENSOR
>         args {
>           type_id: TFT_STRING
>         }
>       }
>       args {
>         type_id: TFT_TENSOR
>         args {
>           type_id: TFT_INT32
>         }
>       }
>     }
>   }
> }
> 
> 2022-10-18 16:53:07.189851: W tensorflow/core/framework/dataset.cc:768] Input of GeneratorDatasetOp::Dataset will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
> Epoch 1/15
> Traceback (most recent call last):
>   File "C:\Users\Public\Public Apps\bumble-bot-main\main.py", line 73, in <module>
>     main()
>   File "C:\Python39\lib\site-packages\click\core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Python39\lib\site-packages\click\core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "C:\Python39\lib\site-packages\click\core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Python39\lib\site-packages\click\core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "C:\Users\Public\Public Apps\bumble-bot-main\main.py", line 38, in main
>     train_model()
>   File "C:\Users\Public\Public Apps\bumble-bot-main\train.py", _**line 80, in train_model
>     model.fit(ds_train, epochs=epochs, validation_data=ds_test, verbose=2)**_
>   File "C:\Python39\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
>     raise e.with_traceback(filtered_tb) from None
>   File "C:\Python39\lib\site-packages\keras\engine\training.py", line 1395, in fit
>     raise ValueError('Unexpected result of `train_function` '
> ValueError: Unexpected result of `train_function` (Empty logs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.

Also I did test the two solutions proposed in the error, maybe I did them wrong but they both didn't seem to do anything (they didn't cause any errors though).

**Comment by ndumais** [comment]
Some extra info on the data that's passed to model.fit, that might cause the issue?

> * DS_TRAIN
> <PrefetchDataset element_spec=(TensorSpec(shape=(8, 224, 224, 3), dtype=tf.float32, name=None), TensorSpec(shape=(8, 2), dtype=tf.float32, name=None))>
> 
> * EPOCHS
> 15
> 
> * DS_TEST
> <BatchDataset element_spec=(TensorSpec(shape=(8, 224, 224, 3), dtype=tf.float32, name=None), TensorSpec(shape=(8, 2), dtype=tf.float32, name=None))>

**Comment by ndumais** [comment]
Ok, after I was able to test some more, turns out the issue had to do with my dataset. Seems to work fine with more data, just did a bit of reading on test vs train, and now I get why it randomly gets assigned to one or the other, and that's probably also why the dataset was incomplete. Is there an upside to going random instead of 50/50? Anyways, closing this!

Désolé!
